### PR TITLE
Bump deCONZ to 2.05.78

### PR DESCRIPTION
**Pull request by stickpin**
Bump deCONZ to 2.05.78

Release notes: https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_78

Resolves: #1428 #1431

### CODE REVIEW

**Comment by DaveRuijter** [comment]
Is there a way to use this in my local installation? Or will this be included in the master soon?

I'm having severe issues with the deCONZ add-on right now and I'm positive that this bump will fix it (not 100% sure, but I want to find out, before investing more time debugging or reinstalling my current system again).

**Comment by pvizeli** [comment]
let's hope it end not in a desaster like the last one...

**Comment by fi-sch** [comment]
Wouldn't it be better to wait for official release before bumping? As I can see this is one of beta pre-releases which will appear every 15th of each month. It is not said that it's stable already.

**Comment by pvizeli** [comment]
Nothing work stable since 2.05.7x - This release work currently with 50 bulbs better as the .75 version

**Comment by DaveRuijter** [comment]
The issues I experienced are solved with the latest update (not sending events to HA).

**Pull request merged**
