### PR TITLE
Telldus core

### PR DESCRIPTION
**Pull request by endor-force**
Added a base package for Telldus-core for @pvizeli to continue bild upon for sockets to be exposed to homeassistant.

https://github.com/home-assistant/hassio/issues/247

use inside home-assistant:
```yaml
host: core-tellstick
port: 50800
```

### CODE REVIEW

**Comment by pvizeli** [comment]
@endor-force I add `/tmp/TelldusEvents` too but home-assistant (`tellcore-net`) only include the `TelldusClient`, maybe we need update this too...

**Comment by pvizeli** [comment]
I have no build a image from this. Can you test it? You can copy that into local repository. The network name will change to `local-tellstick`

**Comment by endor-force** [comment]
Tried following: 
Installed addon, added config in json.

Problem is.. when telldus daemon launches it seem to overwrite the tellstick.conf, or it lacks the content i have added in the addon config..

The json data i add in the addon config is not existing in tellstick.conf.
Either i have parsed the config wrong or the daemon overwrites for some reason.

In my personal option the best option for tellstick users would be to expose the config file in /config dir for user to edit there since they can
a) easily migrate from (any) other installation
b) if they like to generate the config with a 3rd party gui they can just copy paste the config or data without having to change format to suit the addon.
c) any additional params in tellstick.conf does not need to be maintained in run.sh and config.json.

```

{
  "devices": [
    
      "id": 1,
      "name": "test",
      "protocol": "everflourish",
      "model": "selflearning-switch",
      "house": "A",
      "unit": "1"
    
  ]
}
```

tellstick.conf looks like this after addon/daemon has run:
```
root@hassio:~# docker exec addon_local_tellstick cat /etc/tellstick.conf
user="root"
group="plugdev"
deviceNode="/dev/tellstick"
ignoreControllerConfirmation="false"
controller {
  id=1
  # name=""
  type=2
  serial="A501W"
}
```



```

**Comment by endor-force** [comment]
Also tried if homeassistant could speak with tellstick add-on.
Updated hassio to 0.57.3
Added following in configuration.yaml:
```
tellstick:
    host: local-tellstick
    port: 50800
```
No errors when homeassistant loads. 
I have not tried with switches by altering config.
But when adding: 
```
sensor:
  - platform: yr
 - platform: tellstick
```

Then hassio/homeassistant refuses to start up when restarting after adding the values.
Removing the values and homeassistant starts.. so something is fishy in the communication.

**Comment by pvizeli** [comment]
I will look after weekend into this (and movment is done) and expose the event also into home-assistant.

For the UI config. This will be a core add-on, so it need follow our internal guidelines and one of that say that all things need be done over the UI/API. But feel free to provide a own add-on with your rules after we have made it working 👍 

I think we need follow steps:
1) Make the telldus daemon working
2) Fix the config file generator
3) Include the Event socket into tellcore-net api and home-assistant
4) Maybe we need fix or optimize the socat command

**Comment by endor-force** [comment]
Updated and verified.
Config file generator updated and  works now.
Daemon runs in addon and can communicate with units (locally in it's container not with homeassistant yet)

- [x]     Make the telldus daemon working
- [x]     Fix the config file generator
- [ ]     Include the Event socket into tellcore-net api and home-assistant
- [ ]     Maybe we need fix or optimize the socat command

**Comment by pvizeli** [comment]
I hope my internet coming today and I build a new version

**Comment by pvizeli** [comment]
Rebuild is done. You need remove it and reisntall it

**Comment by endor-force** [comment]
@pvizeli Great!
Addon installs and runs from official source. 
How do we move forward with the interaction to homeassistant?

`2017-11-25 09:48:20 WARNING (MainThread) [homeassistant.setup] Setup of sensor is taking over 10 seconds. 2017-11-25 09:48:26 ERROR (MainThread) [homeassistant.setup] Error during setup of component tellstick Traceback (most recent call last): File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 194, in _async_setup_component component.setup, hass, processed_config) File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__ yield self # This tells Task to wait for completion. File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup future.result() File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result raise self._exception File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run result = self.fn(*self.args, **self.kwargs) File "/usr/lib/python3.6/site-packages/homeassistant/components/tellstick.py", line 97, in setup tellcore_devices = tellcore_lib.devices() File "/usr/lib/python3.6/site-packages/tellcore/telldus.py", line 175, in devices device = DeviceFactory(self.lib.tdGetDeviceId(i), lib=self.lib) File "/usr/lib/python3.6/site-packages/tellcore/library.py", line 257, in check_int_result raise TelldusError(result) tellcore.library.TelldusError: Could not connect to the Telldus Service (-6) 2017-11-25 09:48:37 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting`

**Comment by pvizeli** [comment]
Yeah I  need update tellcore-net

**Comment by endor-force** [comment]
Ok. =)
I took a look at the sockets. and the events socket on port 50801 seems to be the one containing sensor data such as thermometers, most likely also publishing events from remotes..

Example: 
```
local-ssh:~# nc core-tellstick 50801
16:TDRawDeviceEvent66:class:sensor;protocol:fineoffset;id:92;model:temperature;t                                                                              emp:2.2;i1s13:TDSensorEvent10:fineoffset11:temperaturei92si1s3:2.2i1511600775s
```

**Comment by phileasfoggish** [comment]
Thanks for your effort, @pvizeli and @endor-force. I just upgraded hass.io to version 0.58.1 (eagerly awaiting some Tellstick Duo action). Am I supposed to be able to use a switch now, or is there remaining work to do before the functionality can be put to use? Also looking forward to part 2 (3?) when the sensor info will be exposed :-)

**Pull request merged**
