### PR TITLE
Update README.md [add-on: google_assistant]

### PR DESCRIPTION
**Pull request by ericmatte**
After having some troubles to setup this add-on and seeing comments on https://github.com/home-assistant/hassio-addons/issues/654 about the documentation being quite unclear. I decided to help and try to make the readme a little clearer.

---

Fixes https://github.com/home-assistant/hassio-addons/issues/724.

This PR update the README.md with the following changes:
- Streamline setup instructions with sub-steps and annotations
- Remove duplicated instructions
- Fix some steps
- Add simple examples on how to use it
- Add a troubleshooting section

Here is a live example of the update readme:
https://github.com/home-assistant/hassio-addons/blob/bb0eac9c3edd28eae14fbc75e795173132cd9f6f/google_assistant/README.md

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @ericmatte, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#1265).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by ericmatte** [comment]
> Can you offload the documentation part to `DOC.md`?

Sure. Do you have an example on how to correctly format the `DOC.md` file?

I saw in the documentation [this section](https://developers.home-assistant.io/docs/hassio_addon_presentation#adding-documentation) talking about it, but when searching in all the addons in this repo and in the https://github.com/hassio-addons organization, none seems to declare a `DOC.md` file.

Which makes me think it could be unconventional 🤔 

Regards,

**Comment by pvizeli** [comment]
Yeah, it would be the first :) the UI support is pretty new. Try somethings if you like otherwise we can do it also later

**Comment by ericmatte** [comment]
@pvizeli I've pushed the requested changes: https://github.com/home-assistant/hassio-addons/pull/1265/commits/1a2294876a3e01c67e003d5b5ff29cf0e97e72d0

So I moved everything under `## How to use` in `DOC.md`, with a `Click here for the full documentation` link.
I've also kept the same header levels than before moving it.

Let me know if this is ok or not, so I can fix it.
Or if you prefer to finish it later, I have no preferences :)

**Comment by pvizeli** [comment]
I'm not sure if the audio part is correct documented. Since we use PulseAudio, there is only one choice inside add-on for ALSA

**Comment by ericmatte** [comment]
> I'm not sure if the audio part is correct documented. Since we use PulseAudio, there is only one choice inside add-on for ALSA

Yeah I saw that too with my own setup.
That part, I kept it like it was before. Imho, we should juste remove that sentence to be simplified with something like so:
```diff
-     1. In the "Audio" section, select the input and output audio devices to use for the Assistant and hit "**Save**". On a Raspberry Pi 3, `ALSA device 0` is the built-in headset port and `ALSA device 1` is the HDMI port.
+     1. In the "Audio" section, select the input and output audio devices to use for the Assistant and hit "**Save**".
```

**Comment by ericmatte** [comment]
Hey @pvizeli,

About the `DOC.md`, on my the Google Assistant SDK add-on in my Supervisor,
I just don't see the documentation, and if I click on the `Click here for the full documentation` link (which works on GitHub), it redirects me to the same page (`/hassio/addon/core_google_assistant/info`) with a double side-panels:

image

I don't think that this is the expected behaviour haha.

I'm on Home Assistant 0.109.1.

**Pull request merged**
