### PR TITLE
Bump deCONZ to 2.05.79

### PR DESCRIPTION
**Pull request by kropp**
Bump deCONZ to 2.05.79

Release notes: https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_79

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @kropp, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#1470).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
Please link up the release notes in the PR descriptions.

At this point, I don't see any releases or release announcements. This means there is also no indicator on the stability on the release version you are bumping.

**Comment by domoritz** [comment]
The changelog is out: https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_79.

**Comment by kropp** [comment]
@domoritz thanks, updated the description
@frenck sorry, I was too excited about OSRAM Mini Switch integration added to the latest version. Will wait until Release Notes are published next time.

**Pull request closed without merging**
