### PR TITLE
Version bumps/update CHANGELOG for check_config and git_pull

### PR DESCRIPTION
**Pull request by Censored3**

### CODE REVIEW

**Comment by pvizeli** [comment]
Please make a PR per topic otherwise I can't build and upload it. Thanks

**Comment by Censored3** [comment]
@pvizeli I bumped version by .1 for both check_config and git_pull. check_config doesn't have a CHANGELOG so it's only the version. git_pull incorporates 2 fixes for one version (see my other PRs). That's why I did the bumps in a separate PR.

Should I split them up and increment version by +0.2?

**Comment by pvizeli** [comment]
Yes, one PR for git_pull and one PR for check_config they bump the version +0.1 and provide a changelog (if they is not exists, create one)

**Comment by Censored3** [comment]
Closing to resubmit

**Pull request closed without merging**
