### PR TITLE
Add the hotword detected toptic to out, following https://docs.snips.…

### PR DESCRIPTION
**Pull request by Romkabouter**
…ai/reference/hermes

I believe the detected topic should be out as well. This way other systems can respond to the hotword detection of snips.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @Romkabouter, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#622).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
Can you pin the snips version inside dockerfile?

**Comment by Romkabouter** [comment]
Errr sorry, I do not know what pinning is?

**Comment by pvizeli** [comment]
https://www.balena.io/blog/our-dockerfile-tips-tricks/

**Comment by Romkabouter** [comment]
Hmmm ok, I don't understand what you want me to do sorry to say.
Do you want me to update the version to 5.3? I am a bit new to this....

**Comment by pvizeli** [comment]
Or to that version they the add-on currently runs. The problem is if I rebuild this add-on again you change we run into issues. The initial creator of this add-on didn't pin the snips version, all other doesn't matter. Now we have a not reproducible state and every update give a big unknown

**Comment by Romkabouter** [comment]
Ah yes, ok. I understand and will see how far I get. Thanks for the help.

**Comment by Romkabouter** [comment]
Pinned to version 0.63.2, please check

**Comment by pvizeli** [comment]
Thanks

image

Please revert file permission change that I can merge it 👍

**Comment by Romkabouter** [comment]
File permission change? Do you mean file version instead?

**Comment by pvizeli** [comment]
No, you change all permissions to 755 from 644 / see on https://github.com/home-assistant/hassio-addons/pull/622/files

**Comment by Romkabouter** [comment]
Yes I see, I was not aware of that. I just forked and clone the repo om my Mac...

**Pull request merged**
