### PR TITLE
custom_deps, let PYPI variable accept comma seperated 

### PR DESCRIPTION
**Pull request by mories76**
comma seperated value can be used to install multiple packages where one depend on another to be build.

(my second PR ever, already messed up the first one, so please let me know if I am doing this the right way)

### CODE REVIEW

**Comment by pvizeli** [comment]
What is wrong with the array?

**Comment by mories76** [comment]
I want to use a custom component which uses pyaes, sleekxmpp and nefit-client, when installing them with one pip install command the dependency for nefit-client isn't met.
Installing them one by one solves the issue

**Comment by pvizeli** [comment]
The config is a array, you can but all modules into this array and install it with one call

**Comment by kunago** [comment]
I also need to install multiple pypi packages and even though I am properly setting the JSON array, I always get an error on install.

**Comment by pvizeli** [comment]
What kind of error? We could try to fix that.

**Comment by mories76** [comment]
I've had the same invalid requirement issue when using the array
"pypi": [ "pyaes", "sleekxmpp", "nefit-client" ]

I also tried
"pypi": [ "pyaes sleekxmpp nefit-client" ]

I think it has something to do with the outer quotation on the --no-dependecies parameter.
But even then when trying to install multiple packages in one pip install command from the command line in a debugging ssh session Nefit-client doesn't install because it needs the pyaes to be installed first.
Apparently pip doesn't install the packages one by one, [https://github.com/pypa/pip/issues/1386](url) might be related.
So my idea was to issue multiple pip install command for each value in the array.

Converting the json array to a bash array didn't work me, so O went for the comma seperated options.

@pvizeli The next time i will raise an issue first to investigate any further, before a PR

**Comment by kunago** [comment]
@mories76 : I also tried various syntaxes and everything failed except for a situation when I inserted just a single pip package; then it worked fine although with no dependencies installed.

**Pull request closed without merging**
