### PR TITLE
Improve DNS-OVH documentation

### PR DESCRIPTION
**Pull request by lambtho12**
Give more details about the API Key requirements for DNS challenge with OVH, following [certbot documentation](https://certbot-dns-ovh.readthedocs.io/en/stable/). 
Added example configuration and details about api_endpoint.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @lambtho12, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#1491).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by TheGroundZero** [comment]
Wouldn't it be better to also limit the scope of the OVH API credentials?

See #1427
> I limited my permissions to GET/POST/PUT/DELETE on /domain/zone/parent.tld instead of /domain/zone/*

So for `homeassistant.domain.com`

* ``GET /domain/zone/domain.com``
* ``PUT /domain/zone/domain.com``
* ``POST /domain/zone/domain.com``
* ``DELETE /domain/zone/domain.com``


Instead of 

* ``GET /domain/zone/*``
* ``PUT /domain/zone/*``
* ``POST /domain/zone/*``
* ``DELETE /domain/zone/*``

**Comment by lambtho12** [comment]
Yes that would probably be preferable if it works. Did you test that? I just copied what was in the certbot docs.

**Comment by TheGroundZero** [comment]
I recently redid the installation, since I previously had issues (the issues mentioned in #1427 are mine).

You first need to visit https://eu.api.ovh.com/createApp/ to create an API Application.
image

Then you get the `Application Key` and `Application Secret`
image

They you either use the [API Explorer](https://eu.api.ovh.com/console/#/auth/credential#POST) or send a cURL request to the [API endpoint](https://eu.api.ovh.com/1.0/auth/credential).
image

You then get a validation URL where you'll need to authenticate with your OVH account to validate the consumerKey
image


Almost there ...
image

**Comment by lambtho12** [comment]
Well I don't get it... It seems that what you are doing does not work. 

On the other hand the change I proposed in this pull request works properly. Did you tired to proceed as I suggested with similar yaml syntax for the add-on config (and maybe just change the ami permission to be more restrictive as you suggested)?

**Comment by TheGroundZero** [comment]
I copied the syntax from your documentation and used the more restrictive permissions as I proposed.

The "application" is valid and active
image

**Comment by lambtho12** [comment]
Yes, but certbot cannot do the challenge and provide you the certificates. Right?

If that is the case, then the issue is with certbot itself and not this add-on I believe.

**Comment by TheGroundZero** [comment]
I'll try some more and note my findings in #1427, to avoid cluttering this PR.

**Pull request merged**
