### PR TITLE
Copy backup of config folder to persistent storage (/config folder) to fix #1000

### LINKED ISSUE #1000: git_pull does not recreate previous files, breaking whole installation
When git_pull starts, it does not recreate the Homeassistant files that were previously there since installation (database, `.storage` folder)

## Steps to recreate

* Plain new Hass.io installation RPi 3
* Enable Git_pull addon
* Configure it:
```json
{
  "deployment_key": ["redacted"], 
  "restart_ignore": [
    "ui-lovelace.yaml", 
    ".gitignore", 
    "README.md", 
    "generate-config.py"
  ], 
  "repository": "git@.../homeassistant.git", 
  "auto_restart": false, 
  "git_remote": "origin", 
  "deployment_user": "", 
  "deployment_password": "", 
  "repeat": {
    "active": true, 
    "interval": 7200
  }, 
  "deployment_key_protocol": "rsa", 
  "git_branch": "master", 
  "git_prune": false, 
  "git_command": "pull"
}
```
* Start add-on

## Before start:

* `apk add tree`
* tree -a
```
config $ tree -a
.
├── .HA_VERSION
├── .cloud
├── .storage
│   ├── auth
│   ├── auth_provider.homeassistant
│   ├── core.area_registry
│   ├── core.config
│   ├── core.config_entries
│   ├── core.entity_registry
│   ├── core.restore_state
│   ├── hassio
│   ├── onboarding
│   └── person
├── automations.yaml
├── configuration.yaml
├── deps
├── groups.yaml
├── home-assistant_v2.db
├── scenes.yaml
├── scripts.yaml
├── secrets.yaml
└── tts
```
## After start
```
.
├── .git
... git folder stuff...
├── .gitignore
├── README.md
├── automations.yaml
├── configuration.yaml
├── generate-config.py
├── scenes.yaml
└── secrets.yaml
```
## The logs

```
Check SSH connection
[Warn] No valid SSH connection for git@...
[Info] Start adding SSH key
[Info] Setup deployment_key on id_rsa
[Warn] Git repostory doesn't exist
[Info] Backup configuration to /tmp/config-2020-01-15_20-43-41
[Info] Start git clone
Cloning into '/config'...
[Info] Checking if something has changed...
[Info] Something has changed, checking Home-Assistant config...
Error: Testing configuration at /config
Failed config
  General Errors: 
    - Error loading /config/configuration.yaml: Secret http_password not defined
Successful config (partial)
[Error] Configuration updated but it does not pass the config check. Do not restart until this is fixed!
```

The last error regarding `http_password` is coming from the secrets.yaml which has the contents of a new clean installation. the default is missing the `http_password`.
```
config $ cat secrets.yaml 

# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
some_password: welcome
```
The secrets.yaml is being overridden by this line: https://github.com/home-assistant/hassio-addons/blob/master/git_pull/data/run.sh#L60.
But I would like to provide that file from git repo as well.

## Expectation

I expected git_pull to leave the previous files alone or at least recreate from /tmp/config in all cases. So, if git_pull fails in any step, revert from backup automatically. Otherwise Homeassistant won't start after a reboot of the host because core files are missing.

Also, there should be an option to also provide the secrets.yaml from git as well. As I expect to manage the COMPLETE homeassistant configuration through git, so I don't have to setup manual secrets and other stuff. Everything should be automated through config-as-code (DevOps principle). this way I can easily replace the current instance with a new installation should the RPi break (which its SD card does from time to time).

However, even with the SSH server addon I cannot seem to even recover the contents from /tmp, as this dir is empty... Probably because git_pull is its own docker container and thus has a different /tmp. This is inconvenient.

### PR DESCRIPTION
**Pull request by mnbf9rca**
should fix #1000 and at least provide a way to undo #968 by creating a backup of /config in /config/config-<datetime>

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @mnbf9rca, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#1152).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
We have our own backup system called snapshot. You can make a snapshot of the folder if you like. That is the modern variant they we want follow. Use simple the CLI for this inside the script

**Comment by mnbf9rca** [comment]
@pvizeli this isnt trying to create a backup solution. The script destructively alters the /config folder on activation, and so the original authors had already thought to keep a backup of the /config folder to allow the user to undo it. However, the backup is stored inside the container, which means it's lost as soon as the container restarts, and it's not accessible to most users. This PR simply puts that backup in the /config folder.

Perhaps there should be an automated snapshot before _any_ add-in is installed but that's a different issue.

**Comment by pvizeli** [comment]
I agree. Update the PR to create a snapshot of the homeassistant folder before he update the config and we can merge this 👍

**Comment by mnbf9rca** [comment]
Cool. Any pointers to documentation for the API to create a snapshot?

**Comment by pvizeli** [comment]
`ha help snapshots`

**Pull request closed without merging**
