### PR TITLE
update deCONZ

### PR DESCRIPTION
**Pull request by agners**
* add aarch64 version

  * add armv7 version

### CODE REVIEW

**Comment by frenck** [comment]
So how would that work?

- Considering the fact this file isn't changed? <https://github.com/home-assistant/hassio-addons/blob/master/deconz/build.json>
- armv7 is added, but what is the use case? Since deCONZ is shipped for armhf. armv7 devices for Hass.io will fall back to armhf...
- The aarch64 is beta... Not sure if we want to ship that, especially since Hass.io is able to fall back to armhf on (most of) those devices

**Comment by agners** [comment]
Sorry I rushed this pull request this morning because I realized @pvizeli is working on the same thing. I should have put WIP into the description

**Comment by pvizeli** [comment]
@agners are fine with this?

**Comment by agners** [comment]
@pvizeli after that last fix looks good to me! Thanks for picking this up!

**Comment by agners** [comment]
@pvizeli I haven't seen aarch64 to become available (although 3.5 is), do I have to do something to refresh container metadata or something?

**Comment by pvizeli** [comment]
It fetches all time the best arch match on every update. So if you click on update, they should see that the new aarch64 match better and take this image

**Comment by agners** [comment]
@pvizeli you are right, checked again on the device, and it indeed installed the right image: `homeassistant/aarch64-addon-deconz`. What confused me is that on the plugin page it still shows that aarch64 | no badge...

**Pull request merged**
