### PR TITLE
Enable autoscale for DeCONZ noVNC

### PR DESCRIPTION
**Pull request by wovka88**
On the laptop it is difficult to use the noVNC page because it does not fit on the screen. I have activated the scaling for the noVNC plugin.

### CODE REVIEW

**Comment by pvizeli** [comment]
Is that tested?

**Comment by wovka88** [comment]
Testet on Edge, Chrome and iPad, works fine for me.

**Review by pvizeli — APPROVED** [review]

**Comment by ottelo9** [comment]
How does this work? I still have scroll bars ...

**Comment by frenck** [comment]
@ottelo9 Please don't use closed PRs for support or reporting bugs.

If you are in need of support, please use the community forum or join our Discord chat. If you want to report a bug, please file an issue here on GitHub.

Thanks 👍

**Pull request merged**
