### PR TITLE
deCONZ 2.05.67 / new udev functions

### PR DESCRIPTION
**Pull request by pvizeli**
Fix: #670

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Was just busy creating a bump PR 🤣

**Comment by sweebee** [comment]
when (approximately) will this be merged/released?

**Comment by pvizeli** [comment]
After I get my test system back and I'm able to test this PR. Today or tomorrow I think

**Comment by somuelle-tmt** [comment]
@pvizeli Did you get your system back?

**Pull request merged**
