### PR TITLE
add websocket listener config (plain and ssl)

### PR DESCRIPTION
**Pull request by ToSa27**
defaults to same config as the original (plain mqtt enabled, all other disabled) but adds ability to configure websockets listeners for both plain and ssl

Fix: #338

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @ToSa27, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#342).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by ToSa27** [comment]
@pvizeli done - please check again.
I would have celled it 1.1 because there are no breaking changes, just an added feature which should qualify for a minor increase not a major but looking at other addons it seems like you don't make that distinction in this repo, hence I did the requested change to 2.0

**Comment by pvizeli** [comment]
Please update the documentation on website too

**Comment by pvizeli** [comment]
Fix: #338

**Pull request merged**
