### PR TITLE
Update firmware upgrade section

### PR DESCRIPTION
**Pull request by bverkron**
Spin off of this PR https://github.com/home-assistant/home-assistant.io/pull/15306. I believe this is the right place for this information.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @bverkron, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#1640).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by bverkron** [comment]
Unsure what this `Initialize builds` error means exactly. Don't feel like this is enough context for me to understand exactly what I need to do to resolve it.

`Error: The head commit for this pull_request event is not ahead of the base commit. Please submit an issue on this action's GitHub repo.`

I attempted to follow the suggested flow through Github to fork, edit, commit, submit PR.

**Comment by bverkron** [comment]
Cannot figure out why this failed so re-submitted via this PR which succeeded.
https://github.com/home-assistant/hassio-addons/pull/1642

**Comment by frenck** [comment]
This is a bug in the phoscon application, not the add-on. A bug should be raised with Dresden instead.

**Pull request closed without merging**
