### PR TITLE
zwave: Update Open-ZWave version

### PR DESCRIPTION
**Pull request by uSpike**
Fixes https://github.com/home-assistant/core/issues/36649 with https://github.com/OpenZWave/open-zwave/issues/2246

Diff: https://github.com/OpenZWave/open-zwave/compare/d2de6990389888850e936894080e4096c822e379...1661e647d42c3e5a59f8291eabbdf2854a938b97

### CODE REVIEW

**Comment by frenck** [comment]
This is actually not the latest version (at the time of the creation of this PR).
Any specific reason for that?

**Comment by uSpike** [comment]
@frenck that was not my intention... I created this PR immediately after https://github.com/OpenZWave/open-zwave/pull/2247 was merged.  I'd be happy to update to the current HEAD if you'd prefer.

**Comment by frenck** [comment]
Yes, lets bump it to `6cec95bbb128e6a287ba8184d0281526f2edd195`.

While you are at it, could you bump ozw-admin to `167180c9ac64ffd699f8c4048ecb8b6c5532d86d`?

Please make sure to bump the version of the add-on a patch version and add both the changes to the changelog.

Thanks 👍

**Comment by uSpike** [comment]
Alright, should be good-to-go.

**Comment by uSpike** [comment]
I fixed merge conflicts.

**Pull request merged**
