### PR TITLE
mosquitto: Add missing login configuration details

### PR DESCRIPTION
**Pull request by ThomDietrich**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @ThomDietrich, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#1127).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @ThomDietrich, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#1127).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by frenck** [comment]
Could you please sign the CLA so we can merge this? Thanks!

**Comment by ThomDietrich** [comment]
Welcome ;)

**Comment by ThomDietrich** [comment]
On second thought - I believe we would be more consistent adding this in the main config example further up. Let me add another commit

**Comment by ThomDietrich** [comment]
Done. Feel free to further edit and merge after. Best!

**Comment by frenck** [comment]
I liked your previous edit better.

Adding commented out YAML is confusing, furthermore, the configuration example just became invalid as well.

I suggest reverting your last commit.

**Comment by ThomDietrich** [comment]
Not sure why commenting out would be confusing :) But yeah one can see it either way.

About the invalid: Sorry didn't test. I am having a first test run with HA and just my fresh-pair-of-eyes point of view: Declaring something optional but then still requiring it in the configuration is quite strange and not consistent throughout all components.

**Comment by ThomDietrich** [comment]
Ready to merge btw ;)

**Pull request merged**
