### PR TITLE
Update to Revision 112 of OpenZwave

### PR DESCRIPTION
**Pull request by Spartan-II-117**
Update to most recent Z-Wave Version to fix crash on kwikset  zwave deadbolts.

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
Here's the diff:
https://github.com/OpenZWave/open-zwave/compare/6cf372959ee88baabfe68742297e7b13f57fef14...7eaae21b3248a82f841900a27ec9702d144f53cc

**Comment by pvizeli** [comment]
Bump version of the add-on + update changelog

**Comment by Spartan-II-117** [comment]
@pvizeli Done.

**Comment by MartinHjelmare** [comment]
@Spartan-II-117 may I ask what devices you tested with in your setup? Have you experienced crashes before this update with the add-on?

**Comment by Spartan-II-117** [comment]
@MartinHjelmare I have two Kwikset 910 Zwave deadbolts, and the 0.5.2 version crashed on enumerating them every time.

**Comment by Spartan-II-117** [comment]
Unfortunately despite this working in the upstream docker container, this does not work within the add-on. I'm not sure how this system is any different from the upstream branch, but i know i'm not the only one experiencing these crashes.

**Pull request merged**
