### PR TITLE
TellStick - Added stdin, clarified desc. and config

### PR DESCRIPTION
**Pull request by endor-force**
- Added Logo
- Added stdin support for hassio addon_stdin calls to tdtool
- Added clarification in description 
- Added second device in example configuration to better visualise formatting.

- [x] Update add-on documentation ( i will do this.)

### CODE REVIEW

**Comment by endor-force** [comment]
I do not have a good solution to this word splitting thing..
The bash has been confirmed to work just fine..

**Comment by tyldum** [comment]
@endor-force Tried  --${input} ?

**Comment by tyldum** [comment]
Ah, it wants you to do 
`if ! msg="$(tdtool \"--${input})\""; then`
In case $input contains spaces

**Comment by endor-force** [comment]
Yay.. should be "$input" to preserve whitespaces..  \" would escape the double qoutes in to the command.

**Comment by endor-force** [comment]
Documentation updated:
https://github.com/home-assistant/home-assistant.github.io/pull/4137

**Comment by pvizeli** [comment]
I build it with new base images (alpine 3.7)

**Pull request merged**
