### PR TITLE
GitPull: add support for ssh cloned GitHub repositories

### PR DESCRIPTION
**Pull request by rpanfili**
I tried to support the exit code/output returned by GitHub using a repository cloned using ssh (e.g. private repos, etc) accordingly [this official GitHub help page](https://help.github.com/articles/testing-your-ssh-connection/)

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @rpanfili, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#241).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
I long line :)

**Comment by rpanfili** [comment]
@pvizeli I know :sweat_smile: but otherwise I got some issues with the travis `shellcheck` routine checking the exit code indirectly and the output at the same time trying to avoid code duplication

**Comment by pvizeli** [comment]
Yeah no problem. I push it out in a hour

**Pull request merged**
