### PR TITLE
Modify git_pull to support reset as well as pull

### PR DESCRIPTION
**Pull request by matt-FFFFFF**
I have been using this git pull plugin but it used to complain that the local files had been modified when they hadn't. I could successfully do a git pull using remote tools like vscode but this plugin would fail.  So, I wanted to add an option to support ```git reset --hard``` to support overwriting local changes with the remote.

This has been exposed using an additional option called git_command.  This can be pull (default) or reset.

Other changes:
- I have also added a check that the local git repo is set to the correct remote URL.
- I have added 2 extra options to allow for the branch and remote names being non-standard. Sensible defaults have been specified for each.
- Modified the validate config function to report when there are changes even if auto restart is off

Am happy to update the docs if this is merged.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @matt-FFFFFF, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio-addons#350).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by matt-FFFFFF** [comment]
Re: Travis is errors on double quotes

The double quotes are there, they are just escaped ```\"``` due to already being inside double quotes.

**Comment by pvizeli** [comment]
Thanks

**Comment by pvizeli** [comment]
Can you also update the documentation on website?

**Comment by matt-FFFFFF** [comment]
Sure, will do this in the next day or so.

**Pull request merged**
